version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: host
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  backend:
    image: marktai/backend:latest
    build: ./backend
    network_mode: host
    volumes:
      - ./posts:/app/posts
      - ./frontend/upload:/app/upload
    depends_on:
      - db
    restart: always
#   frontend:
#     image: clover/frontend:latest
#     build: ./frontend
#     volumes:
#       - ./frontend/src:/app/src
#       - ./frontend/build:/app/build
#     ports:
#       - "7003:3000"
#     restart: always
  nginx:
    image: marktai/nginx:latest
    build: ./nginx

    network_mode: host
    volumes:
      - ./frontend/:/home/mtai/repos/marktai.com/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - backend
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  database:
