version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true 
    volumes:
      - database:/var/lib/mysql
    restart: always
  backend:
    image: marktai/backend:latest
    build: ./backend
    volumes:
      - ./posts:/app/posts
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
#   frontend:
#     image: clover/frontend:latest
#     build: ./frontend
#     volumes:
#       - ./frontend/src:/app/src
#       - ./frontend/build:/app/build
#     ports:
#       - "7003:3000"
#     restart: always
  nginx:
    image: marktai/nginx:latest
    build: ./nginx
    volumes:
      - ./frontend/:/home/mtai/repos/marktai.com/
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  database:
