title = "Bacon Ipsum2"
ignore = false
subtitle = "Better than that Lorem nonsense"
author = "Mark Tai"
image = "img/bacon-bg.jpg"
created = 2015-07-27T07:32:00-08:00
modified = 2015-05-27T07:32:00-08:00
content = [
	"Here is bacon2 text",
	"And another one!"
]
