title = "Ignore"
ignore = true
subtitle = "Better than that Lorem nonsense"
author = "Mark Tai"
image = "img/bacon-bg.jpg"
created = 2000-07-27T07:32:00-08:00
modified = 2000-05-27T07:32:00-08:00
content = [
	"This should be ignored"
]
