version: '3.3'

services:
  acme.sh:
    image: neilpang/acme.sh
    command: daemon
    volumes:
      - ../data/acme.sh:/acme.sh
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    env_file: .env
    restart: always
